# Add the configs below to your jekyll _config.yaml

podcast:
  title: [Title]
  description: [Description]
  url: /podcast.xml
  author: [Author]
  email: [Email]
  logo: [Podcast Logo URL] # Podcast logo URL, 1400 – 3000 pixels
  lang: [Language] # http://www.loc.gov/standards/iso639-2/php/code_list.php
  category: [Category] # https://help.apple.com/itc/podcasts_connect/#/itc9267a2f12
  subcategory: [Subcategory]
  explicit: [Explicit State] # true or false
  complete: [Complete State] # yes or no